input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["host.docker.internal:9200"]
    index => "node-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # Watch this terminal!
}